# Generated by Django 5.0.4 on 2024-05-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='zipçode',
            new_name='zipcode',
        ),
    ]
